import TableInput from "./TableInput";

export const Tablecolumns = [
  {
    accessor: "itemname",
    label: "Domain Name",
    priorityLevel: 1,
    position: 1,
    minWidth: 150,
  },
  {
    accessor: "Bids",
    label: "Bids/Offers",
    priorityLevel: 2,
    position: 2,
    minWidth: 150,
  },
  {
    accessor: "Traffic",
    label: "Traffic",
    priorityLevel: 3,
    position: 3,
    minWidth: 150,
  },
  {
    accessor: "Estimated",
    label: "Estimated Value",
    priorityLevel: 4,
    position: 4,
    minWidth: 150,
  },
  {
    accessor: "Price",
    label: "Price",
    priorityLevel: 5,
    position: 5,
    minWidth: 150,
  },
 
  {
      accessor: "lastName",
      label: "Last Name",
      priorityLevel: 6,
      position: 6,
      minWidth: 150,
      CustomComponent: TableInput,
    },
    {
      accessor: "Timeleft",
      label: "Time left",
      priorityLevel: 7,
      position: 7,
      minWidth: 150,
    },
 
];
export const Tablerows = [
    {
      id: 1,
      itemname: "Domain.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹14,300",
      Timeleft:"24D 12HR",
    },
    {
      id: 2,
      itemname: "jewellers.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹10,300",
      Timeleft:"5D 12HR",
    },
    {
      id: 3,
      itemname: "khazana.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹13,300",
      Timeleft:"3D 12HR",
    },
    {
      id: 4,
      itemname: "Terces.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹15,300",
      Timeleft:"4D 12HR",
    },
    {
      id: 5,
      itemname: "Aruhi.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹11,600",
      Timeleft:"3D 2HR",
    },
    {
      id: 6,
      itemname: "Vishwas.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹9,500",
      Timeleft:"3D 8HR",
    },
    {
      id: 7,
      itemname: "Kalyan.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹20,300",
      Timeleft:"8D 2HR",
    },
    {
      id: 8,
      itemname: "Sam.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹18,300",
      Timeleft:"5D 8HR",
    },
    {
      id: 9,
      itemname: "Shining.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹15,800",
      Timeleft:"3D 6HR",
    },
    {
      id: 10,
      itemname: "Aagam.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹16,800",
      Timeleft:"8D 14HR",
    },
    {
      id: 11,
      itemname: "Great.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹11,400",
      Timeleft:"9D 12HR",
    },
    {
      id: 12,
      itemname: "Talented.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹12,500",
      Timeleft:"4D 12HR",
    },
    {
      id: 13,
      itemname: "Best.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹9,500",
      Timeleft:"3D 12HR",
    },
    {
      id: 14,
      itemname: "Fine.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹6,100",
      Timeleft:"6D 12HR",
    },
    {
      id: 15,
      itemname: "Amazing.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹9,900",
      Timeleft:"8D 12HR",
    },
    {
      id: 16,
      itemname: "Amith.gold",
      Bids: "0" ,
      Traffic:"-",
      Estimated: "-",
      Price:"₹7,200",
      Timeleft:"9D 12HR",
    },
  ];
