let DestinationData = [
    {
      id: 1,
      img: require("../media/gold2.jpg"),
      title: "SIRI Jewels",
      bed: "Palvancha",
      feet: "150 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      person: 2,
    },
    {
      id: 2,
      img: require("../media/gold2.jpg"),
      title: "Pabbathi Jewels",
      bed: "Kothagudem",
      feet: "150 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 3,
      img: require("../media/gold2.jpg"),
      title: "New jewels",
      bed: "Warangal",
      feet: "500 sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 4,
      img: require("../media/gold2.jpg"),
      title: "Technology jewels",
      bed: "KU cross",
      feet: "400 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 5,
      img: require("../media/gold2.jpg"),
      title: "Sam jewels",
      bed: "Hanamkonda",
      feet: "250 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 6,
      img: require("../media/gold2.jpg"),
      title: "Happy Jewels",
      bed: "Warangal",
      feet: "350 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 7,
      img: require("../media/gold2.jpg"),
      title: "Famous Jewels",
      bed: "Subedari",
      feet: "450 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 8,
      img: require("../media/gold2.jpg"),
      title: "Golden Jewels",
      bed: "Hyderabad",
      feet: "200 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
    {
      id: 9,
      img: require("../media/gold2.jpg"),
      title: "Royal Jewels",
      bed: "Madikonda",
      feet: "150 Sq.feet",
      desc: "We'll get from air terminal while you comfortable on your ride, We'll get from air terminal while you comfortable on your ride.....",
      price: "Explore",
      checkIn: "",
      checkOut: "",
    },
  ];


export default DestinationData;